// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQzztxsvLpAPc-vOmJzrZGlv2E_ye3lEM',
    appId: '1:613921929030:web:fdaeba9d5160562882d747',
    messagingSenderId: '613921929030',
    projectId: 'alfardos-app',
    authDomain: 'alfardos-app.firebaseapp.com',
    storageBucket: 'alfardos-app.firebasestorage.app',
    measurementId: 'G-SPLCH4T7NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvLsaBprx7DYpbdwAijZi7F8loxIKE_U',
    appId: '1:613921929030:android:445467bd6c45079982d747',
    messagingSenderId: '613921929030',
    projectId: 'alfardos-app',
    storageBucket: 'alfardos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4OLOPh1Q3yT3N6JRDKWaKQB1Z4mgBYxQ',
    appId: '1:613921929030:ios:553a75bde077b9d282d747',
    messagingSenderId: '613921929030',
    projectId: 'alfardos-app',
    storageBucket: 'alfardos-app.firebasestorage.app',
    iosBundleId: 'com.example.appAlfardos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4OLOPh1Q3yT3N6JRDKWaKQB1Z4mgBYxQ',
    appId: '1:613921929030:ios:2219d143244c8ba982d747',
    messagingSenderId: '613921929030',
    projectId: 'alfardos-app',
    storageBucket: 'alfardos-app.firebasestorage.app',
    iosBundleId: 'af.alfardos.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQzztxsvLpAPc-vOmJzrZGlv2E_ye3lEM',
    appId: '1:613921929030:web:7051a4740b99714c82d747',
    messagingSenderId: '613921929030',
    projectId: 'alfardos-app',
    authDomain: 'alfardos-app.firebaseapp.com',
    storageBucket: 'alfardos-app.firebasestorage.app',
    measurementId: 'G-K1CYFTQ1Y4',
  );
}
